# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  publish-release:
    docker:
      - image: circleci/golang:1.9
      # specify any bash command here prefixed with `run: `
    working_directory: /go/src/github.com/qlik-oss/k-apis
    steps:
      - checkout
      - run: 
          name: "Publish Release"
          command: | 
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/


      